### ISSUE TITLE
always return invalid client_id

### ISSUE THREAD

**Issue by lukedoomer** [cmd-johnson/ckb-cloud#1]
client-side
`curl http://localhost:3007/clients/`
`["{b516845c-d0bb-4985-b518-c45e8df4ce58}"]`

`curl http://localhost:3007/clients/{b516845c-d0bb-4985-b518-c45e8df4ce58}/keys/`
`&quot;Invalid client_id&quot;`

`curl http://localhost:3007/clients/b516845c-d0bb-4985-b51-c45e8df4ce58/keys/`
`&quot;Invalid client_id&quot;`

server-side
`Local server started at socket /tmp/ckb-cloud`
`REST-server listening on port 3007`
`Client connected: {b516845c-d0bb-4985-b518-c45e8df4ce58}`
`Clients available: ["{b516845c-d0bb-4985-b518-c45e8df4ce58}"], requested: b516845c-d0bb-4985-b518-c45e8df4ce58`
`"Invalid client_id"`

is it a bug?

**Comment by cmd-johnson** [comment]
Good catch, I only tested the endpoints using Postman, which automatically URL-encodes the curly brackets; curl doesn't do that. Try to replace the opening one with `%7B` and the closing one with `%7D`, that should do the trick.

curl uses [URL globbing](https://ec.haxx.se/cmdline-globbing.html) by default, which in this particular case makes curl interpret the request URL as if the brackets weren't there at all.

Instead of URL-encoding the brackets, you could also add `-g` to the curl-request to turn off URL globbing. That will send literal `{` and `}` to the server. (Although note that those are actually no safe characters in a URL and should generally be avoided.)

**Comment by cmd-johnson** [comment]
Also note that the current API is everything but stable, but every feedback is greatly appreciated!

**Comment by lukedoomer** [comment]
would you consider to remove `{` and `}` from the format of http url? I think using `%` or `{}` is kind of awkward. Pure character is much more resonable.

**Comment by cmd-johnson** [comment]
Granted, I don't like that format either, but for some reason it's the format Qt chose for UUID-strings.
The IDs are generated and set by the ckb-cloud-client, I'll open an issue over there.

**Comment by cmd-johnson** [comment]
Okay, I just removed the curly braces from the string-representation of UUIDs.
However the client-ID is only generated when adding the ckb-cloud client-effect in ckb, so you'll either have to remove the effect and add it again, or edit the effect properties and manually remove the brackets in the 'Client ID'-field.
Note that you can name your client whatever you like, it doesn't have to be a UUID but can be any string.

**Comment by lukedoomer** [comment]
Excellent changes. Thank you.
